server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://43.139.40.2:3306/vz_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zwz1235789
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  redis:
    host: 43.139.40.2
    port: 6379
    password: zwz1235789
    timeout: 10000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 打开七牛云，找到密钥管理，把相关信息填写到下面3行，会被huanf-blog工程的OOSTest类获取
myoss:
  xxaccessKey: mvWGDmt7gruhOs_EbmIjiQ47AHcqBVGuJaZjgnKl
  xxsecretKey: ZOMSp7YtWwEe2xtFNSb8goueDSL2KiT00OnRIaw3
  xxbucket: vzer-blog